### ISSUE TITLE
BUG - GitPages - Processo de ER

### ISSUE THREAD

**Issue by ggomesbr** [mdsreq-fga-unb/2022.1-Monitoramento-de-Obras#20]
**Descrição do Bug**
Na tela de Processo de Engenharia de Requisitos o markdown está bugando no tópico "Elicitação de Requisitos".

**Comportamento Esperado**
Não deveria aparecer as três hashtags.

**Screenshots**
![image](https://user-images.githubusercontent.com/78509975/176833354-db3a2992-6aaa-4769-b379-86b5bac91404.png)

**Comment by ArthurFerreiraRodrigues** [comment]
Correção validada.
