### ISSUE TITLE
BUG - GitPages - Tela Id Visual Faltando Histórico de Versão

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [mdsreq-fga-unb/2022.1-Monitoramento-de-Obras#22]
**Descrição do Bug**
A seguinte tela do GitPages está sem a tabela de histórico de versões.
![image](https://user-images.githubusercontent.com/69909375/176906783-a0c76796-fddc-471b-9167-62ceb5fc1e90.png)

**Comment by dartmol203** [comment]
eu faço, quem fez o inicial dessa pagina, Arthur ou Ana?

**Comment by ArthurFerreiraRodrigues** [comment]
Eu que fiz a página toda.

**Comment by dartmol203** [comment]
tabela adicionada
